import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./styles/globals.css";
import "@/app/styles/globals.css";
import "./styles/main.scss"

// const geistSans = localFont({
//   src: "./public/fonts/GeistMonoVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./public/fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
